### ISSUE TITLE
Possible Enchancement: Dedicated Emulator Section

### ISSUE THREAD

**Issue by muffinV136** [oxters168/OxShell#14]

**Comment by oxters168** [comment]
Hi, thanks for the suggestion. I'm not sure I understand it, can you elaborate some more please?

**Comment by IAmAGitHubb** [comment]
Basically he wants a section of emulators. (Retroarch, Aethersx2 and more)

**Comment by oxters168** [comment]
If I understand the request correctly, it is already possible to achieve. When in the home menu, you can long press anywhere on the touch screen to bring up a context menu. Alternatively you can use the X button on a Nintendo/XBox gamepad, or the square button on a Playstation gamepad. In this context menu there is an option to add a new column. You can name it `Emulators` and give it an icon of your choosing. If you do not see the option to create a new column, make sure you are not inside an item; go as far back on the home menu as you can.

After the column is created, go to the item you'd like to have in there and use the context menu to choose to begin moving it. Then by dragging on the touch screen or using the dpad on a controller, you can move the item in the direction of the new column until it is inside of it. Then tap anywhere, or press the A button on a Nintendo/XBox gamepad, or the cross button on a Playstation gamepad. This will release the item into the column. Repeat these steps for all the items you'd like in the column.

In the current state of the app, it is unclear that this is possible or that a context menu even exists, I do apologize for that. I'll work on making it more clear in the future.

**Comment by oxters168** [comment]
Closed due to inactivity
