### ISSUE TITLE
PNG files don't support transparency

### ISSUE THREAD

**Issue by HollyCeuin** [oxters168/OxShell#15]
Chose a transparent png file for a column icon, black background appears.
![Screenshot_20230820-070717](https://github.com/oxters168/OxShell/assets/96226750/61267f1c-3e9e-40fc-bb42-bf5a8177d42f)

**Comment by oxters168** [comment]
Thanks for bringing this to my attention, I'll see what I can do to fix it.

**Comment by oxters168** [comment]
This [pull request](https://github.com/oxters168/OxShell/pull/16) fixes the issue and is now available in the [latest release](https://github.com/oxters168/OxShell/releases/tag/v1.3.1). Thanks again for bringing this to my attention and let me know of any suggestions or other issues you run into.
