### ISSUE TITLE
404 page not found error on f-droid site

### ISSUE THREAD

**Issue by nathgit** [oxters168/OxShell#28]
I tried to install through the f-Droid store, & got an error, so I went to the F-Droid site to download it, & try to install it manually, but I just get a "404 page not found" error. Was it removed? It shows up in the app, just not on the site.

**Comment by oxters168** [comment]
Ox Shell is not directly available on F-Droid. It is still possible to get it from F-Droid though. If you add the [IzzyOnDroid](https://apt.izzysoft.de/fdroid/) repository to your repositories list in F-Droid then Ox Shell should become available to you. From my understanding this repository adds projects on Github that have android releases to F-Droid.

**Comment by nathgit** [comment]
I did add that repo. It shows in the store, it just gives an error when I try to install it.

**Comment by oxters168** [comment]
I just tried downloading it on my phone from F-Droid and it worked just fine for me. Maybe you're facing some kind of DNS issue? Try changing the DNS on your device and see if that makes any difference. It's a bit of a shot in the dark but it's all I can think of.

It could also be an issue with F-Droid or IzzyOnDroid, in which case you'd need to consult them.

Another solution is to download the apk from the [latest release](https://github.com/oxters168/OxShell/releases/tag/v1.3.2) and install it manually.

**Comment by oxters168** [comment]
Closed due to inactivity
