### ISSUE TITLE
List of planned features?

### ISSUE THREAD

**Issue by Quackdoc** [oxters168/OxShell#6]
Has a couple of benefits, lets people know what to look forward to, and lets people who may wish to support the project something to potentially work on if they dont have any idea's themselves

**Comment by oxters168** [comment]
You make a good point, I'll add a list soon. Feel free to suggest some yourself as well!

**Comment by Quackdoc** [comment]
Great app, been using it for about an hour or so now. Im really liking it, already reported a bug, but here are some features 

-  parse `android:isGame="true"` for games

many game applications like dolphin and retroarch use ` android:isGame="true"` instead of `android:appCategory="game"`. this causes them not to show up

- toggle `leanback` mode this comes in two parts,

one to separate "tv optimized" applications from non optimized games (not really that important but a nice to have), 

and the second is to launch the application in `leanback mode`. 
for an example application launching dolphin using a TV launcher (for example [Flauncher which is fully open source](https://gitlab.com/flauncher/flauncher) but now abandoned, or [tsynik's leanback](https://github.com/tsynik/LeanbackLauncher) which is a modification for leanback launcher). will open dolphin with a TV/controller centric UI that is suitable for.

- refresh the screen for newly installed apps.

not familiar with the best way of doing this myself. but even a manual update would IMO be nice as a short term solution

these are the major features that I can think off of the top of my head, I've already tested it has a home screen and it has been a pretty good experience this far, will certainly be recommending it to friends

**Comment by oxters168** [comment]
The app now has leanback support and I added a way to get the background working properly on an Android TV. I also added the check for isGame flag on apps when categorizing them and the feature to add newly installed apps to the home screen. Let me know if you have any other suggestions or issues, thanks!
