### ISSUE TITLE
Keyboard based input device support

### ISSUE THREAD

**Issue by Quackdoc** [oxters168/OxShell#8]
there are a plethora of devices that can be used for inputs that emulate keyboards this is very common for "air mice" devices and other misc remotes and controllers

- directional keys and keypad directional keys work,
- enter button does not work (code 66: KEYCODE_ENTER)
- keypad enter does not work (code 160: KEYCODE_NUMPAD_ENTER)
- menu key not working (ideally should bring up the menu) (code 82: KEYCODE_MENU)

**Comment by oxters168** [comment]
I have added keyboard support in the latest release
